name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker run -d --publish 80:80 --hostname localhost wlsf82/gitlab-ce 
        
    - name: Wait for GitLab to be ready
      run: sleep 30

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Usar a versão mais recente LTS do Node.js

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run test
