name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker run -d --publish 80:80 --hostname localhost wlsf82/gitlab-ce 
        
    - name: Wait for GitLab to be ready
      run: sleep 80

    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
    - name: Run Cypress tests
      run: npm run test # Aqui está o comando correto, sem o "npm run build"
